import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const montserrat = Montserrat({
	variable: "--font-montserrat-sans",
	subsets: ["latin"],
});


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="sk">
			<body className={`${montserrat.variable}`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
