import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import CartProvider from "@/components/CartProvider/CartProvider";
import Footer from "@/components/Footer/Footer";
import Script from "next/script";


const montserrat = Montserrat({
	variable: "--font-montserrat-sans",
	subsets: ["latin"],
});


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="sk">
			<head>
				<meta name="google-site-verification" content="FSaPwNNHa_INuIokyRiaONgJt97b84T43F6xqFTkR_8" />
			</head>
			<body className={`${montserrat.variable}`}>
				<Script
					id="zoho-salesiq-init"
					strategy="beforeInteractive"
					dangerouslySetInnerHTML={{
						__html: `
							window.$zoho = window.$zoho || {};
							$zoho.salesiq = $zoho.salesiq || {
								ready: function() {
									console.log('Zoho SalesIQ initialized');
								}
							};
						`
					}}
				/>
				<Header />
				<CartProvider>
					{children}
				</CartProvider>
				<Footer />

				{/* Zoho SalesIQ Chat Widget - Main Script */}
				<Script
					id="zoho-salesiq-widget"
					src="https://salesiq.zohopublic.eu/widget?wc=siq6baa26158f6358677c5d4ab519fd128520a6948174d7839f102574e3dbd3f4c2"
					strategy="lazyOnload"
				/>

			</body>
		</html>
	);
}
